config/routes.rb
Rails.application.routes.draw do

  scope 'espy' do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  #    concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new

  root to: "catalog#index"
    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    #concerns [:exportable, :marc_viewable]
  end
  
  get "/manifest" => "catalog#manifest"
  
  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get "fields", to: "fields#index"

  end
	# For docker healthcheck
    get 'health', to: proc { [200, {}, ['OK']] }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController

  include BlacklightRangeLimit::ControllerOverride

  include Blacklight::Catalog
  #include Blacklight::Marc::Catalog


  configure_blacklight do |config|
    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response
    #
    ## Should the raw solr document endpoint (e.g. /catalog/:id/raw) be enabled
    # config.raw_endpoint.enabled = false

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      rows: 10
    }

    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select'
    #config.document_solr_path = 'get'

    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    # solr field configuration for search results/index views
    config.index.title_field = 'name'
    #config.index.display_type_field = 'format'
    config.index.thumbnail_field = 'thumbnail_ss'

    config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    #config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    #config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    #config.add_show_tools_partial(:citation)

    config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')

    # solr field configuration for document/show views
    #config.show.title_field = 'title_tsim'
    #config.show.display_type_field = 'format'
    #config.show.thumbnail_field = 'index_card_download'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    config.add_facet_field 'state', label: 'State', limit: 10, index_range: 'A'..'Z'
    config.add_facet_field 'record_type', label: 'Record Type'
    config.add_facet_field 'icpsr_record', label: 'Espy File Record'
    config.add_facet_field 'year_execution', label: 'Date of Execution', range: true
    config.add_facet_field 'gender_assigned', label: 'Gender Assigned'
    config.add_facet_field 'race', label: 'Race'
    config.add_facet_field 'age', label: 'Age', range: true
    config.add_facet_field 'crime_convicted_of', label: 'Crime Convicted of', limit: 10, index_range: 'A'..'Z'
    config.add_facet_field 'enslaved', label: 'Enslaved'
    config.add_facet_field 'compensation_case', label: 'Compensation Case'
    config.add_facet_field 'execution_method', label: 'Execution Method', limit: 10, index_range: 'A'..'Z'
    config.add_facet_field 'jurisdiction', label: 'Jurisdiction', limit: 10, index_range: 'A'..'Z'
    config.add_facet_field 'county_name', label: 'County Name', limit: 10, index_range: 'A'..'Z'
    
    config.add_facet_field 'format', label: 'Format'
    config.add_facet_field 'pub_date_ssim', label: 'Publication Year', single: true
    config.add_facet_field 'subject_ssim', label: 'Topic', limit: 20, index_range: 'A'..'Z'
    config.add_facet_field 'language_ssim', label: 'Language', limit: true
    config.add_facet_field 'lc_1letter_ssim', label: 'Call Number'
    config.add_facet_field 'subject_geo_ssim', label: 'Region'
    config.add_facet_field 'subject_era_ssim', label: 'Era'

    config.add_facet_field 'example_pivot_field', label: 'Pivot Field', :pivot => ['format', 'language_ssim']

    config.add_facet_field 'example_query_facet_field', label: 'Publish Date', :query => {
       :years_5 => { label: 'within 5 Years', fq: "pub_date_ssim:[#{Time.zone.now.year - 5 } TO *]" },
       :years_10 => { label: 'within 10 Years', fq: "pub_date_ssim:[#{Time.zone.now.year - 10 } TO *]" },
       :years_25 => { label: 'within 25 Years', fq: "pub_date_ssim:[#{Time.zone.now.year - 25 } TO *]" }
    }


    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field 'title_tsim', label: 'Title'
    config.add_index_field 'title_vern_ssim', label: 'Title'
    #config.add_index_field 'first_name', label: 'First Name'
    #config.add_index_field 'last_name', label: 'Last Name'
    config.add_index_field 'date_execution', label: 'Date Execution'
    config.add_index_field 'state', label: 'State', link_to_facet: true
    config.add_index_field 'gender_assigned', label: 'Gender Assigned', link_to_facet: true
    config.add_index_field 'age', label: 'Age'
    config.add_index_field 'race', label: 'Race', link_to_facet: true
    config.add_index_field 'county_name', label: 'County Name', link_to_facet: true
    config.add_index_field 'author_tsim', label: 'Author'
    config.add_index_field 'author_vern_ssim', label: 'Author'
    config.add_index_field 'format', label: 'Format'
    config.add_index_field 'language_ssim', label: 'Language'
    config.add_index_field 'published_ssim', label: 'Published'
    config.add_index_field 'published_vern_ssim', label: 'Published'
    config.add_index_field 'lc_callnum_ssim', label: 'Call number'

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field 'title_tsim', label: 'Title'
    config.add_show_field 'title_vern_ssim', label: 'Title'
    config.add_show_field 'subtitle_tsim', label: 'Subtitle'
    config.add_show_field 'subtitle_vern_ssim', label: 'Subtitle'
    config.add_show_field 'author_tsim', label: 'Author'
    config.add_show_field 'author_vern_ssim', label: 'Author'
    config.add_show_field 'format', label: 'Format'
    config.add_show_field 'url_fulltext_ssim', label: 'URL'
    config.add_show_field 'url_suppl_ssim', label: 'More Information'
    config.add_show_field 'language_ssim', label: 'Language'
    config.add_show_field 'published_ssim', label: 'Published'
    config.add_show_field 'published_vern_ssim', label: 'Published'
    config.add_show_field 'lc_callnum_ssim', label: 'Call number'
    config.add_show_field 'isbn_ssim', label: 'ISBN'
    
    config.add_show_field 'name', label: 'Name'
    config.add_show_field 'record_type', label: 'Record Type', link_to_facet: true
    config.add_show_field 'icpsr_record', label: 'Espy File Record'
    config.add_show_field 'icpsr_id', label: 'Espy File ID'
    config.add_show_field 'state', label: 'State', link_to_facet: true
    config.add_show_field 'circa_date_execution', label: 'Circa'
    config.add_show_field 'date_execution', label: 'Date Execution'
    config.add_show_field 'circa_date_crime', label: 'Circa'
    config.add_show_field 'date_crime', label: 'Date Crime'
    config.add_show_field 'age', label: 'Age'
    config.add_show_field 'gender_assigned', label: 'Gender Assigned', link_to_facet: true
    config.add_show_field 'race', label: 'Race', link_to_facet: true
    config.add_show_field 'crime_convicted_of', label: 'Crime Convicted of', link_to_facet: true
    config.add_show_field 'enslaved', label: 'Enslaved'
    config.add_show_field 'owner_name', label: 'Owner Name'
    config.add_show_field 'compensation_case'
    config.add_show_field 'execution_method', label: 'Execution Method', link_to_facet: true
    config.add_show_field 'jurisdiction', label: 'Jurisdiction', link_to_facet: true
    config.add_show_field 'county_name', label: 'County', link_to_facet: true

app/views/catalog/_home_text.html.erb
<div class="jumbotron text-center">
  <h1 class="jumbotron-heading">Espy Project Execution Records</h1>

  <p class="lead">Telling the Stories of over 15,000 Individuals Executed in what is now the United States since 1608</p>

  <p>
  </p>
</div>


<p>The Espy Project uses the M. Watt Espy Papers and the Espy File dataset to provide documentation for American executions.
</p>

<div class="row">
    <div class="col-md-9">
        <ul>
            <li><a href="https://archives.albany.edu/web/espyfields/">Description of metadata fields</a></li>
            <li><a href="https://archives.albany.edu/catalog?f[collection_sim][]=M.+Watt+Espy+Papers&f[resource_type_sim][]=Dataset">CSV Datasets</a></li>
        </ul>
        <p>M. Watt Espy spent most of his life documenting the death penalty. He drew on a network of sources around the country to gather reference material from newspaper accounts, corrections records, local histories, and more. Espy then typed summaries of each case on index cards which provide vivid, if problematic, accounts of each case. In 1984, the National Science Foundation awarded a grant to Espy, John Ortiz Smykla  and the University of Alabama (SES 84-09725) to create a dataset based on Espy’s materials for academic research. This was released as <a href="https://doi.org/10.3886/ICPSR08451.v5">Executions in the United States, 1608-2002: The ESPY File (ICPSR 8451)</a>. Espy and his family later donated the collection to the M.E Grenander Special Collections & Archives at the University at Albany, SUNY between 2008 and 2016. In 2016, the Council on Library and Information Resources (CLIR) funded <a href="http://registry.clir.org/projects/23081088">The Digital Archive of Executions in the United States, 1608-2002: Digitization and Access to the M. Watt Espy Papers</a> to digitize the index card summaries and reference material and make them available online. This site is one of the outcomes of that project.</p>
    </div>
    <div class="col-md-3">
        <figure class="figure">
            <%= image_tag('espy_photo_web.jpg', alt: "M. Watt Espy in his office at the Capital Punishment Research Project.") %>
            <figcaption class="figure-caption">M. Watt Espy in his office at the Capital Punishment Research Project.</figcaption>
        </figure>
    </div>
</div>

<p>The total number of American executions is unclear. Many cases have limited or conflicting documentation, particularly before the 20th century when documentation was sparse and executions were more regular events. We tried to be more inclusive and include cases found in Espy’s materials that were omitted from the Espy File dataset. This includes executions in other jurisdictions that took place in what is now the United States, such as Native American executions and executions in Spanish, French, or Russian colonies. We also included many cases where the outcome was unclear. Cases were classified as “Documented,” or “Underdocumented” to make these distinctions transparent. Cases with original source material or confident and detailed citations were classified as “Documented.” There are also cases where the reason for their omission from the Espy File is unclear.</p>
<p>The descriptions in both the original source material and Espy’s index card summaries may be offensive or harmful. In particular, we recognize that this material often fails to represent marginalized groups of people accurately and respectfully. Additionally, the data coding in the Espy File dataset was also not always appropriate. We have attempted to remove harmful language in the places we directly control, such as the display application and Espy Data Fields. Still, since the information we have for each case is based solely on the existing documentation, we inevitably perpetuated the omissions and distortions of that documentation.</p>
<p>Please <a href="https://albany.libwizard.com/f/contactus?i_have_a_questi=Special%20Collections%20%26%20Archives">contact us</a> for any further clarification.</p>

<div class="row">
  <div class="col-md-9">
      <h4>More about the Espy Project:</h4>
        <ul>
          <li><a href="https://archives.albany.edu/web/espyproject/">Espy Project Announcement</a>, April 2017</li>
          <li><a href="http://registry.clir.org/projects/23081088">CLIR Grant Announcement</a>, 2016</li>
          <li><a href="https://archives.albany.edu/description/catalog/apap301">M. Watt Espy Papers</a></li>
          <li><a href="https://archives.albany.edu/web/2017/10/06/espy_project_fall_update.html">Espy Project Fall Update</a>, October 2017</li>
          <li><a href="https://gregwiedeman.com/slides/code4lib2019.html#/">Code4Lib presentation, by Gregory Wiedeman</a>, 2019 February</li>
          <li><a href="https://archives.albany.edu/web/2019/05/13/disparities_in_documentation.html">Disparities in Documentation, by Sheri Sarnoff</a>, May 2019</li>
          <li><a href="https://archives.albany.edu/web/2019/05/15/working_with_challanging_or_anonymous_records.html">Working with Challanging or Anonymous Records, by Amanda Partridge</a>, May 2019</li>
          <li><a href="https://archives.albany.edu/web/2019/05/20/missing_executions_from.html">Missing Executions from 1860-1875 Mississippi, by Miles Lawlor</a>, May 2019</li>
        </ul>
    </div>
    <div class="col-md-3 clir mb-4">
        <a href="https://www.clir.org/hiddencollections"><img alt="Council on Library and Information Resources Logo" src="https://archives.albany.edu/web/oldDrupal/img/clir.gif"></a>
    </div>
</div>


app/views/catalog/_show.html.erb
<% doc_presenter = show_presenter(document) %>

<div class="row">
    <div class="col-lg-8">
        <% if doc_presenter.document["index_card"] || doc_presenter.document["big_card"] || doc_presenter.document["reference_material"] %>

            <div id="mirador-viewer" style="width:100%; height:600px; background-color: #000"></div>
            <%= javascript_include_tag "/espy/mirador/mirador.min.js" %>
            <script>
              document.addEventListener("DOMContentLoaded", function () {
                const isMobile = window.innerWidth <= 768;
                Mirador.viewer({
                  id: "mirador-viewer",
                  windows: [{
                    manifestId: "/espy/manifest?id=<%= doc_presenter.document["id"] %>",
                    allowFullscreen: true,
                    defaultSideBarPanel: 'none',
                    sideBarOpenByDefault: false,
                    zoomControls: true,
                    thumbnailNavigationPosition: isMobile ? 'off' : 'far-bottom',
                  }],
                  workspace: {
                      showZoomControls: true,
                  },
                  themes: {
                    light: {
                      palette: { primary: { main: '#46166B' } }
                    }
                  },
                  workspaceControlPanel: { enabled: false },
                  window: {
                    allowClose: false
                  }
                });
              });
            </script>
	<% end %>
    </div>

    <div class="col-lg-4">
        <%= render 'show_tools' %>
        <% skip_list = ["circa_date_execution", "circa_date_crime", "index_card", "index_card_id", "index_card_files", "index_card_uri", "index_card_download", "big_card", "big_card_id", "big_card_files", "big_card_uri", "big_card_download", "reference_material", "reference_material_id", "reference_material_files", "reference_material_uri", "reference_material_download"] %>
    
        <%# default partial to display solr document fields in catalog show view -%>
        <dl class="row dl-invert document-metadata">
          <% doc_presenter.fields_to_render.each do |field_name, field, field_presenter| -%>
            <% unless skip_list.include? field_name %>
                <% if field_name == "index_card_aspace" %>
                    <dt class="blacklight-<%= field_name.parameterize %> col-md-6"></dt>
                    <dd class="blacklight-<%= field_name.parameterize %> col-md-6"><a href="<%= field_presenter.render %>">Index Card File</a></dd>
                <% elsif  field_name == "big_card_aspace" %>
                    <dt class="blacklight-<%= field_name.parameterize %> col-md-6"></dt>
                    <dd class="blacklight-<%= field_name.parameterize %> col-md-6"><a href="<%= field_presenter.render %>">Large Card File</a></dd>
                <% elsif  field_name == "reference_material_aspace" %>
                    <% field_presenter.render.split("; ").each do |ref_link| %>
                        <dt class="blacklight-<%= field_name.parameterize %> col-md-6"></dt>
                        <dd class="blacklight-<%= field_name.parameterize %> col-md-6"><a href="<%= ref_link %>">Reference Material File</a></dd>
                    <% end %>
                <% else %>
                    <dt class="blacklight-<%= field_name.parameterize %> col-md-6"><%= render_document_show_field_label document, label: field_presenter.label, field: field_name %></dt>
                    <dd class="blacklight-<%= field_name.parameterize %> col-md-6"><%= field_presenter.render %></dd>
                <% end %>
            <% end %>
          <% end -%>
        </dl>
        <%= link_to fields_path, class: 'btn btn-primary mb-4' do %>
          <%= blacklight_icon :'info-fill', aria_hidden: true %> About these fields
        <% end %>
        
        <% datasets = {"Alaska": "https://archives.albany.edu/concern/daos/h702qr462", \
            "Alabama": "https://archives.albany.edu/concern/daos/1544c675j", \
            "Hawaii": "https://archives.albany.edu/concern/daos/w0892w21f", \
            "Oregon": "https://archives.albany.edu/concern/daos/qr46rk03m", \
            "Wyoming": "https://archives.albany.edu/concern/daos/6w924w50g"} %>
            
        <% if false %>
          <%= link_to datasets[doc_presenter.document["state"].to_sym], class: 'btn btn-primary mb-4' do %>
            <%= blacklight_icon :'table', aria_hidden: true %> Dataset for all <%= doc_presenter.document["state"] %> Executions
          <% end %>
        <% end %>
    </div>
</div>

app/views/catalog/_show_main_content.html.erb
<%= render 'previous_next_doc' if @search_context %>

<% @page_title = t('blacklight.search.show.title', :document_title => document_show_html_title, :application_name => "Espy Project Execution Records").html_safe %>
<% content_for(:head) { render_link_rel_alternates } %>

<div id="document" class="document <%= render_document_class %>" itemscope  itemtype="<%= @document.itemtype %>">
  <div id="doc_<%= @document.id.to_s.parameterize %>">
    <%= render_document_partials @document, blacklight_config.view_config(:show).partials %>
  </div>
</div>

<% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
  <!--
       // COinS, for Zotero among others.
       // This document_partial_name(@document) business is not quite right,
       // but has been there for a while.
  -->
  <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(document_partial_name(@document)) %>"></span>
<% end %>

app/views/catalog/_show_sidebar.html.erb
<%# render 'show_tools' %>

<% unless document.more_like_this.empty? %>
  <div class="card">
    <div class="card-header">More Like This</div>
    <div class="card-body">
      <%= render collection: document.more_like_this,
                 partial: 'show_more_like_this',
                 as: :document %>
    </div>
  </div>
<% end %>

app/views/catalog/_show_tools.html.erb
<% if show_doc_actions? %>
  <div class="show-tools">
      <%= render_show_doc_actions @document do |config, inner| %>
        <div class="<%= config.key %>">
          <%= inner %>
        </div>
      <% end %>
  </div>
<% end %>

app/views/catalog/show.html.erb
<% if current_search_session %>
  <div id="appliedParams" class="clearfix constraints-container">
    <%= render 'start_over' %>
    <%= link_back_to_catalog class: 'btn btn-outline-secondary' %>
  </div>
<% end %>
<%= render_document_main_content_partial %>

<% content_for(:sidebar) do %>
  <%= render_document_sidebar_partial @document %>
<% end %>